In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
# Define the vocabulary size
voc_size = 10000

In [8]:
# OneHot representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[5158, 8308, 6216, 6206],
 [5158, 8308, 6216, 7426],
 [5158, 5065, 6216, 7880],
 [9692, 2094, 8006, 7605, 5217],
 [9692, 2094, 8006, 7605, 8512],
 [1307, 5158, 5794, 6216, 594],
 [4196, 1457, 4800, 7605]]

In [10]:
# Word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5158 8308 6216 6206]
 [   0    0    0    0 5158 8308 6216 7426]
 [   0    0    0    0 5158 5065 6216 7880]
 [   0    0    0 9692 2094 8006 7605 5217]
 [   0    0    0 9692 2094 8006 7605 8512]
 [   0    0    0 1307 5158 5794 6216  594]
 [   0    0    0    0 4196 1457 4800 7605]]


In [12]:
# Feature represenatation 
dim = 10

In [14]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 312ms/step


array([[[-0.00248398, -0.03892484, -0.03891088,  0.04879595,
         -0.0343532 , -0.04410932, -0.04312726,  0.00737132,
          0.01281803,  0.02473737],
        [-0.00248398, -0.03892484, -0.03891088,  0.04879595,
         -0.0343532 , -0.04410932, -0.04312726,  0.00737132,
          0.01281803,  0.02473737],
        [-0.00248398, -0.03892484, -0.03891088,  0.04879595,
         -0.0343532 , -0.04410932, -0.04312726,  0.00737132,
          0.01281803,  0.02473737],
        [-0.00248398, -0.03892484, -0.03891088,  0.04879595,
         -0.0343532 , -0.04410932, -0.04312726,  0.00737132,
          0.01281803,  0.02473737],
        [ 0.04987847,  0.00785832,  0.00197067,  0.00797271,
          0.03942025,  0.02552155,  0.01677467, -0.018092  ,
         -0.02302542,  0.03627953],
        [-0.01161858, -0.03703101, -0.04385374,  0.03236734,
          0.01599533,  0.02229258,  0.0254043 ,  0.01574605,
          0.02570466, -0.04324191],
        [ 0.0419698 ,  0.0380665 ,  0.0012303 ,  0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 5158, 8308, 6216, 6206])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 52ms/step


array([[-0.00248398, -0.03892484, -0.03891088,  0.04879595, -0.0343532 ,
        -0.04410932, -0.04312726,  0.00737132,  0.01281803,  0.02473737],
       [-0.00248398, -0.03892484, -0.03891088,  0.04879595, -0.0343532 ,
        -0.04410932, -0.04312726,  0.00737132,  0.01281803,  0.02473737],
       [-0.00248398, -0.03892484, -0.03891088,  0.04879595, -0.0343532 ,
        -0.04410932, -0.04312726,  0.00737132,  0.01281803,  0.02473737],
       [-0.00248398, -0.03892484, -0.03891088,  0.04879595, -0.0343532 ,
        -0.04410932, -0.04312726,  0.00737132,  0.01281803,  0.02473737],
       [ 0.04987847,  0.00785832,  0.00197067,  0.00797271,  0.03942025,
         0.02552155,  0.01677467, -0.018092  , -0.02302542,  0.03627953],
       [-0.01161858, -0.03703101, -0.04385374,  0.03236734,  0.01599533,
         0.02229258,  0.0254043 ,  0.01574605,  0.02570466, -0.04324191],
       [ 0.0419698 ,  0.0380665 ,  0.0012303 ,  0.01356227, -0.01192515,
        -0.04587696,  0.04338386, -0.00028881